apiVersion: v1
kind: Service
metadata:
  name: agreeculture-service
  namespace: agro
spec:
  selector:
    app: agreeculture-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
