apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agreeculture-ingress
  namespace: agro
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: agree.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agreeculture-service
                port:
                  number: 5000
