apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - pgadmin-deployment.yaml
  - pgadmin-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - ingress.yaml

namespace: agro
