apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agro-api.fullname" . }}
  labels:
    app: agro-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: agro-api
  template:
    metadata:
      labels:
        app: agro-api
    spec:
      containers:
        - name: agro-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
